eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/,http://peer3:1113/eureka/

feign:
  #feign use okhttp
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    #是否开启断熔器
    enabled: false
    command:
        default:
          execution:
            timeout:
              enabled: false
  #开启请求压缩功能
  compression:
    request:
      enabled: true
      #指定压缩请求数据类型
      mime-types: text/xml;application/xml;application/json
      #如果传输超过该字节，就对其进行压缩
      min-request-size: 2048
    #开启响应压缩功能
    response:
      enabled: true

server:
  port: 8081
spring:
  application:
    name: web-demo
  output:
  #控制台彩色输出
    ansi.enabled: ALWAYS

logging:
  level:
    com.ngdsoft.client: DEBUG
    com.ngdsoft.api: INFO

debug: false

