spring:
  application:
    name: eureka-server

---
server:
  port: 1111
spring:
  profiles: peer1
eureka:
  instance:
    prefer-ip-address: true
    hostname: peer1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer2:1112/eureka/,http://peer3:1113/eureka/
---
server:
  port: 1112
spring:
  profiles: peer2
eureka:
  instance:
    prefer-ip-address: true
    hostname: peer2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer3:1113/eureka/,http://peer1:1111/eureka/

---
server:
  port: 1113
spring:
  profiles: peer3
eureka:
  instance:
    prefer-ip-address: true
    hostname: peer3
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/

